import React from 'react'
import Navbar from '../Components/navbar';
import Footer from '../Components/footer';
import LeafReveal from '../Components/leafReveal';

export default function Home() {
  return (<>
    <h1>Welcome to Green Guardians!</h1>
    <LeafReveal content={<>
      <h2>Did you know this?</h2>
      This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting. This is interesting.
    </>}/>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non sodales neque sodales ut. Etiam erat velit scelerisque in dictum non. Eu consequat ac felis donec et odio pellentesque. Non nisi est sit amet facilisis magna etiam. Nam aliquam sem et tortor. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Quis auctor elit sed vulputate. Facilisis magna etiam tempor orci eu lobortis elementum. Posuere ac ut consequat semper viverra nam. Suscipit tellus mauris a diam maecenas. In massa tempor nec feugiat nisl pretium fusce id. Nunc mattis enim ut tellus elementum sagittis. Neque volutpat ac tincidunt vitae semper quis lectus. Eros in cursus turpis massa. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a.

    Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Vivamus at augue eget arcu dictum varius duis at consectetur. Id ornare arcu odio ut sem nulla pharetra diam sit. Nunc pulvinar sapien et ligula. Ac auctor augue mauris augue neque gravida in. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Aliquam ultrices sagittis orci a scelerisque. Etiam dignissim diam quis enim. Turpis nunc eget lorem dolor sed. Odio eu feugiat pretium nibh ipsum. Tellus id interdum velit laoreet id donec. Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Felis eget nunc lobortis mattis aliquam faucibus purus in. Sed nisi lacus sed viverra tellus in hac habitasse platea. Fringilla phasellus faucibus scelerisque eleifend. Vel facilisis volutpat est velit egestas dui id. Quisque non tellus orci ac auctor augue mauris.

    Interdum consectetur libero id faucibus nisl. Elit pellentesque habitant morbi tristique senectus et netus et. Sapien nec sagittis aliquam malesuada. Enim diam vulputate ut pharetra sit amet aliquam id diam. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Magna fringilla urna porttitor rhoncus. Quam pellentesque nec nam aliquam. Et pharetra pharetra massa massa ultricies. Morbi leo urna molestie at elementum. Neque laoreet suspendisse interdum consectetur. Faucibus vitae aliquet nec ullamcorper sit amet. Nisl pretium fusce id velit ut tortor. Netus et malesuada fames ac turpis egestas maecenas.

    Viverra nibh cras pulvinar mattis nunc sed blandit libero. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. Sagittis orci a scelerisque purus semper. Feugiat vivamus at augue eget. Sodales neque sodales ut etiam sit. Facilisis magna etiam tempor orci eu. Volutpat ac tincidunt vitae semper quis lectus nulla. Arcu dui vivamus arcu felis bibendum ut tristique et. Nunc congue nisi vitae suscipit. Ipsum dolor sit amet consectetur adipiscing elit. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. In ante metus dictum at tempor commodo ullamcorper. Netus et malesuada fames ac turpis egestas sed. Mattis enim ut tellus elementum sagittis vitae et leo duis. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies.

    Suscipit tellus mauris a diam. In egestas erat imperdiet sed euismod nisi porta lorem. Et egestas quis ipsum suspendisse ultrices gravida. Sit amet purus gravida quis blandit. Sem viverra aliquet eget sit amet tellus cras adipiscing. Pellentesque habitant morbi tristique senectus et netus et malesuada. Sed elementum tempus egestas sed sed risus pretium. Pellentesque massa placerat duis ultricies lacus sed. Tempus egestas sed sed risus pretium quam. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Ut ornare lectus sit amet est placerat in egestas erat. Sed enim ut sem viverra aliquet eget sit amet.

    Est pellentesque elit ullamcorper dignissim cras tincidunt. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Pellentesque diam volutpat commodo sed egestas egestas. Sit amet cursus sit amet dictum sit amet. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Dui nunc mattis enim ut. In nulla posuere sollicitudin aliquam ultrices sagittis orci. Etiam sit amet nisl purus in. Dignissim cras tincidunt lobortis feugiat vivamus at augue. At tellus at urna condimentum mattis pellentesque. Amet massa vitae tortor condimentum lacinia quis vel eros.

    Et malesuada fames ac turpis egestas integer. Mattis aliquam faucibus purus in massa. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Etiam sit amet nisl purus. Aenean euismod elementum nisi quis. Est pellentesque elit ullamcorper dignissim cras. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Senectus et netus et malesuada fames. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Sed arcu non odio euismod lacinia at quis risus. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Augue eget arcu dictum varius duis at.

    Justo donec enim diam vulputate. Magna fringilla urna porttitor rhoncus dolor purus. Lorem sed risus ultricies tristique. Sit amet risus nullam eget felis. Turpis egestas sed tempus urna et pharetra pharetra massa massa. Adipiscing at in tellus integer feugiat scelerisque varius morbi enim. Id porta nibh venenatis cras sed felis eget. Tellus integer feugiat scelerisque varius morbi. Sit amet purus gravida quis. Nunc vel risus commodo viverra. Molestie nunc non blandit massa enim. Vel facilisis volutpat est velit egestas dui. Est lorem ipsum dolor sit amet. Eget nulla facilisi etiam dignissim diam quis enim.

    Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Non nisi est sit amet facilisis magna etiam tempor orci. A scelerisque purus semper eget duis at. Aliquam vestibulum morbi blandit cursus risus at ultrices. Sit amet nisl purus in. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Accumsan tortor posuere ac ut consequat semper. A pellentesque sit amet porttitor. Massa sed elementum tempus egestas sed. Vel risus commodo viverra maecenas accumsan lacus.

    Volutpat est velit egestas dui id ornare arcu odio. Dolor sit amet consectetur adipiscing elit ut. Rhoncus urna neque viverra justo nec ultrices dui. Faucibus nisl tincidunt eget nullam non nisi est. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Viverra aliquet eget sit amet. Nunc non blandit massa enim nec dui nunc mattis. In massa tempor nec feugiat nisl pretium fusce id velit. Imperdiet nulla malesuada pellentesque elit eget. Commodo odio aenean sed adipiscing diam donec. Nunc consequat interdum varius sit amet. Arcu non sodales neque sodales ut etiam sit. Cras semper auctor neque vitae tempus quam. Lacus viverra vitae congue eu consequat ac felis donec.
  </>);
}